server:
  port: 8080

spring:
  application:
    name: back
  profiles:
    include:
      - todo
      - market


feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000